
FROM apache/airflow:2.9.3-python3.11

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jre-headless procps && \
    apt-get clean

USER airflow

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
COPY ./requirements.txt /requirements.txt

ARG AIRFLOW_VERSION=2.9.3
ARG PYTHON_VERSION=3.11
ARG CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

RUN python -V \
 && pip install --no-cache-dir -r /requirements.txt --constraint "${CONSTRAINT_URL}"

ENV PYTHONPATH=/opt/airflow/dags:/opt/airflow/plugins
