FROM apache/airflow:3.0.6

COPY requirements.txt /requirements.txt

ARG AIRFLOW_VERSION=3.0.6
ARG PYTHON_VERSION=3.12
ARG CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

RUN python -V && pip install --no-cache-dir -r /requirements.txt --constraint "${CONSTRAINT_URL}"
